services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

    environment:
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

   
  db:

    image: postgres
    ports:
      - "5432:5432"
   
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
